name: jc-py3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - future=0.18.2
  - numpy=1.20.1
  - scipy=1.6.1
  - matplotlib=3.3.4
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - netCDF4=1.5.6
